[package]
name = "flying-sandbox-monster"
version = "0.1.0"
authors = ["pufferffish <me@windtfw.com>"]

[dependencies]
winapi = "0.2"
kernel32-sys = "0.2"
field-offset = "0.1.1"
libc = "0.2.22"
widestring = "0.2.2"
log = "0.3.9"
